services:
  - type: web
    name: speaker-recognition
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ml_website.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0